[{
	"resource": "/c:/Users/wow_s/OneDrive/Рабочий стол/chat-pleawswewewe-7ed1d3e1805bedef14f01fc7b3462f5383934e9f/components/UserProfileModal.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'useState'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 33,
	"endLineNumber": 10,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wow_s/OneDrive/Рабочий стол/chat-pleawswewewe-7ed1d3e1805bedef14f01fc7b3462f5383934e9f/components/UserProfileModal.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'UserProfile'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 42,
	"endLineNumber": 10,
	"endColumn": 53,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wow_s/OneDrive/Рабочий стол/chat-pleawswewewe-7ed1d3e1805bedef14f01fc7b3462f5383934e9f/components/UserProfileModal.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'useState'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 33,
	"endLineNumber": 11,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wow_s/OneDrive/Рабочий стол/chat-pleawswewewe-7ed1d3e1805bedef14f01fc7b3462f5383934e9f/components/UserProfileModal.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'useState'.",
	"source": "ts",
	"startLineNumber": 12,
	"startColumn": 29,
	"endLineNumber": 12,
	"endColumn": 37,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wow_s/OneDrive/Рабочий стол/chat-pleawswewewe-7ed1d3e1805bedef14f01fc7b3462f5383934e9f/components/UserProfileModal.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'useEffect'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 3,
	"endLineNumber": 16,
	"endColumn": 12,
	"modelVersionId": 2,
	"origin": "extHost1"
}]